name: Latest blog post workflow
on:
  push:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract URLs from sitemap
        id: extract-urls
        run: |
          wget -qO- https://cassiorsfreitas.com/sitemap.xml | grep -oP '<loc>\K[^<]+' > urls.txt

      - name: Pull in cassiorsfreitas.com posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOG"
          feed_list: "urls.txt"
